### ISSUE TITLE
Add TFHE.exp operation

### ISSUE THREAD

**Issue by Dalgerok** [zama-ai/fhevm-solidity#318]
Hi, I see lack of exponential operation in https://docs.zama.ai/fhevm/how-to/operations. I think it can be efficiently implemented using binary exponentiation: https://cp-algorithms.com/algebra/binary-exp.html

**Comment by ScottZSH** [comment]
I think we can consider it

**Comment by immortal-tofu** [comment]
Hi!
It's probably doable in TFHE, even though it's not implemented in tfhe-rs yet. We could add it in the future, but it's not planned at the moment since we don't see many use cases where exponential functions would be useful.
