### ISSUE TITLE
Add some space in ZAMA'S weblink in website for better UX 

### ISSUE THREAD

**Issue by piu738** [zama-ai/fhevm-solidity#376]
As a user it's very uncomfortable to click particular website for ZAMA'S community. Whenever I click on a particular link of a ZAMA'S  community website, sometimes  it clicks another link. 
Because the links are very close to each other.

📍Solution: Add little bit of space Among the web links. It will help better UX for ZAMA'S website and users will love it. Here is the image 👇

![IMG_20240430_140310](https://github.com/zama-ai/fhevm/assets/139789017/e97f55a1-d1c9-4ade-956b-5f759825fcca)

**Comment by piu738** [comment]
@immortal-tofu can u please check it brother ? 🥺

**Comment by immortal-tofu** [comment]
Thank you for the feedback, it has been updated with bigger icons.
