### ISSUE TITLE
A sustainable economy for ZAMA chain 🚀

### ISSUE THREAD

**Issue by piu738** [zama-ai/fhevm-solidity#379]
An innovative idea 💡 

Now a days almost every blockchain has some supply allocated to distribute block rewards to its validators. They share 100% of the token inflation with them.

Solution is simple Zama will do something differently. Zama can share some of the token inflation (eg : 80%) with validators and the remaining 20% with developers.

Also without burning 100% base transaction fees Zama can burn 50% of their base transaction fee and remain 50% share with devolopers. 

Believe me this type of long sustainable incentives model motivate devolopers to build with ZAMA. An useful application always attract more users. More users = More adoption of ZAMA chain. This is a flywheel loop ZAMA can creat if this happen. 

It's a win win situation for devs and end users too. Users could receive incentives from projects building on ZAMA , and they could also get a revenue share if these projects decide to share revenue based on particular interaction.

Keep building guies I belive in ZAMA 🚀

**Comment by piu738** [comment]
@immortal-tofu bro it will be a gamechanger 🙃

**Comment by Sayan7388** [comment]
@immortal-tofu hello sir is it a good idea 💡? Please let me know please
