### ISSUE TITLE
Doc: Simplify the "Decryption" doc

### ISSUE THREAD

**Issue by yuxizama** [zama-ai/fhevm-solidity#497]
Hi team,
During my review of documentation, I found the "Decryption" doc is particularly long and hard to read. I would suggest simply this document to improve readability for users. For example:
- Add section breaks 
- Separate "function/steps explanations" and "parameter explanations", using bullet points instead of paragraphs
Happy to provide further assistance if needed. 🙌
Thank you!

**Comment by poppyseedDev** [comment]
Agree, thanks for creating the issue @yuxizama !
