### ISSUE TITLE
Update tutorials

### ISSUE THREAD

**Issue by immortal-tofu** [zama-ai/fhevm-solidity#533]
https://docs.zama.ai/fhevm/tutorials/see-all-tutorials

+ Update Zama's article

Splitting this one into multiple steps:
 - [x] #555
 - [x] #556
 - [ ] #557
 - [ ] #558

**Comment by poppyseedDev** [comment]
Splitting this one into multiple steps:
 - [ ] adding comments + documentation to the contracts that we already have
 - [ ] updating the See all tutorials page - this will be an ongoing effort
 - [ ] update blog tutorials
