### ISSUE TITLE
unused import in some sol files

### ISSUE THREAD

**Issue by 0xalexbel** [zama-ai/fhevm-solidity#622]
Hi Zama Team! 👋,

If you havent yet spotted it, here are 2 unused imports in 2 solidity files:

1. in "fhevm/gateway/GatewayContract.sol"

```solidity
// Unused import: Neither TFHE nor any of the 'e' types is used.
import "../lib/TFHE.sol";
```

2. in "fhevm-core-contracts/contract/InputVerifier.native.sol" (in fhevm-core-contracts npm package)

```solidity
// Unused import: the constant 'coprocessorAdd' is not used.
import "../addresses/CoprocessorAddress.sol";
```

A personal remark:
I usually enable the solhint "no-global-import" rule following OpenZeppelin pattern. It makes the "import" statements much easier to debug.
https://protofire.github.io/solhint/docs/rules/best-practises/no-global-import.html

Hope it helps!

**Comment by jatZama** [comment]
good catch, we will fix those thanks.

**Comment by jatZama** [comment]
this has been fixed already @immortal-tofu here https://github.com/zama-ai/fhevm-backend/commit/e319d52825622808f24d72ab0adadb66fa7ede25
